# -*- coding: utf-8 -*-
"""kanren.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfetGFZ0rl5fjQiX0zxUki_ERlAW3TFB
"""

pip install kanren

from kanren import facts, Relation, var, run

parent = Relation()
facts(parent,  ("Tomas", "Efrain"),("Tomas", "Jenny"),("Antonio", "Tomas"))
x = var()

run(1, x, parent(x,"Efrain"))

run(2,x,parent("Tomas",x))

y=var()
run(1,x,parent(x,y)),

primos = Relation()
facts(primos,  ("Grover", "Efrain"),("Alex", "Efrain"))

p = var()
run(2, p, primos(p,"Efrain"))